apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: redis-image-
spec:
  podGC:
    strategy: OnPodSuccess # delete pods when workflow is successful
  entrypoint: build-kaniko-image
  arguments:
    parameters:
    - name: git_ref_type
      value: branches
    - name: git_version
  templates:
  - name: build-kaniko-image
    inputs:
      parameters:
      - name: git_ref_type
      - name: git_version
    steps:
    - - name: mirror-image
        templateRef:
          name: flavor-image-mirror-template
          template: "{{inputs.parameters.git_ref_type}}"
        arguments:
          parameters:
          - name: git_repo
            value: https://github.com/bradfordwagner/container-redis.git
          - name: git_version
            value: "{{inputs.parameters.git_version}}"
          - name: repo_name
            value: quay.io/bradfordwagner/redis
          - name: upstream_repo
            value: "{{ item.repo }}"
          - name: upstream_tag
            value: "{{ item.tag }}"
          - name: tag_suffix
            value: "-{{ item.name_override }}-{{ item.tag }}"
          - name: runtime_platforms
            value: "{{ item.runtime_platforms }}"
        withItems:
        - { repo: 'docker.io/redis', tag: '7.0.4-alpine', name_override: redis, runtime_platforms: [linux/amd64, linux/arm64] }

